import Head from "next/head";
const myfonts = require("./_fonts");
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/banner";
import NavBar from "@/components/nav/navbar";
import SectionCard from "@/components/card/section-cards";

// import { disneyVideos } from "./videolist";
import {
  getVideos,
  getPopularVideos,
  getWatchItAgainVideos,
} from "@/lib/videos";
import { verifyToken } from "@/lib/utils";
import useRedirectUser from "@/utils/redirectUsers";
// import { startFetchMyQuery } from "../lib/db/hasura";

export async function getServerSideProps(context) {
  // const userId = "did:ethr:0x46A78b352F31F2966Fb08a6C483a5A3C11a276B5";
  // const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJkaWQ6ZXRocjoweDQ2QTc4YjM1MkYzMUYyOTY2RmIwOGE2QzQ4M2E1QTNDMTFhMjc2QjUiLCJwdWJsaWNBZGRyZXNzIjoiMHg0NkE3OGIzNTJGMzFGMjk2NkZiMDhhNkM0ODNhNUEzQzExYTI3NkI1IiwiZW1haWwiOiJzYXR5YW1yYWoyMzU4QGdtYWlsLmNvbSIsIm9hdXRoUHJvdmlkZXIiOm51bGwsInBob25lTnVtYmVyIjpudWxsLCJ3YWxsZXRzIjpbXSwiaWF0IjoxNjgzMjc1MjI5LCJleHAiOjE2ODM4ODAwMjksImh0dHBzOi8vaGFzdXJhLmlvL2p3dC9jbGFpbXMiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ1c2VyIiwiYWRtaW4iXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoidXNlciIsIngtaGFzdXJhLXVzZXItaWQiOiJkaWQ6ZXRocjoweDQ2QTc4YjM1MkYzMUYyOTY2RmIwOGE2QzQ4M2E1QTNDMTFhMjc2QjUifX0.VYaTOAI2uIkbm45C2RvZDdF31v_eTV5wmIdvY5mOVPQ";

  const { userId, token } = await useRedirectUser(context);
  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

  const disneyVideos = await getVideos("disney%20trailer");
  const productivityVideos = await getVideos("productive videos");
  const travelVideos = await getVideos("travel%20blogs");
  const popularVideos = await getPopularVideos();

  return {
    props: {
      disneyVideos,
      productivityVideos,
      travelVideos,
      popularVideos,
      watchItAgainVideos,
    }, // will be passed to the page component as props //this is ServerSideRendering. data from API is handled by server and then presented to client.
  };
}

export default function Home({
  disneyVideos,
  productivityVideos,
  travelVideos,
  popularVideos,
  watchItAgainVideos,
}) {
  // startFetchMyQuery(); //not needed now
  return (
    <div className={myfonts.roboto + " " + styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username={"raghav@email.com"} />
      <Banner
        title="The Guardians"
        subTitle="The protectors of galaxy"
        imgUrl="/static/theGuardians.jpg"
        videoId="kZropz0-aDk"
      />

      <div className={styles.sectionWrapper}>
        <SectionCard title="Disney" videos={disneyVideos} size="large" />
      </div>
      <div className={styles.sectionWrapper}>
        <SectionCard
          title="Watch it again"
          videos={watchItAgainVideos}
          size="small"
        />
      </div>
      <div className={styles.sectionWrapper}>
        <SectionCard title="Travel" videos={travelVideos} size="small" />
      </div>
      <div className={styles.sectionWrapper}>
        <SectionCard
          title="Productivity"
          videos={productivityVideos}
          size="medium"
        />
      </div>
      <div className={styles.sectionWrapper}>
        <SectionCard title="Popular" videos={popularVideos} size="small" />
      </div>

      {/* <Card imgUrl="/static/theGuardians.jpg" size="large" /> */}
    </div>
  );
}

// imgUrl="/static/theGuardians.jpg , bc the public folder will be served statically.

//my youtube API key : AIzaSyCl4kfHL10llXPp0zFJXGTRmQc2MX4OsSc
