import Head from "next/head";
const myfonts = require("./_fonts");
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/banner";
import NavBar from "@/components/nav/navbar";
import Card from "@/components/card/card";
import SectionCard from "@/components/card/section-cards";

export default function Home() {
  return (
    <div className={myfonts.roboto + " " + styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username={"raghav@email.com"} />
      <Banner
        title="The Guardians"
        subTitle="The protectors of galaxy"
        imgUrl="/static/theGuardians.jpg"
      />

      <div className={styles.sectionWrapper}>
        <SectionCard title="Disney" />
      </div>

      {/* <Card imgUrl="/static/theGuardians.jpg" size="large" /> */}
    </div>
  );
}

// imgUrl="/static/theGuardians.jpg , bc the public folder will be served statically.
